services:
  app:
    container_name: ruby_offers
    build: .
    ports:
      - "30001:3000"
    environment:
      - DATABASE_URL_DEV=postgres://offers_admin:password123@db/user_offers_dev #db is hostname
      - DATABASE_URL_TEST=postgres://offers_admin:password123@db/user_offers_test #db is hostname
    volumes:
      - .:/usr/src/app
    tty: true # attach a terminal
  db:
    container_name: ruby_offers_db_pgsql
    image: postgres:14.5
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=offers_admin
      - POSTGRES_PASSWORD=password123
    volumes:
      - pgsql_db:/var/lib/postgresql/data

volumes:
  pgsql_db: